version: "3.9"

services:
  frontend:
    image: ghcr.io/sashaprovorova/film-react-nest-frontend:latest
    volumes:
      - frontend_dist:/dist
    restart: "no"
  backend:
    image: ghcr.io/sashaprovorova/film-react-nest-backend:latest
    env_file:
      - ./env.prod
    environment:
      DATABASE_HOST: db
      # переход на Mongo
      # DATABASE_HOST: mongo
    depends_on:
      - db
      # - mongo
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: ghcr.io/sashaprovorova/film-react-nest-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    env_file:
      - ./env.prod
    environment:
      POSTGRES_DB: filmdb
      POSTGRES_USER: filmuser
      POSTGRES_PASSWORD: film_nest
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/test/prac.init.sql:/docker-entrypoint-initdb.d/00_init.sql:ro
      - ./backend/test/prac.films.sql:/docker-entrypoint-initdb.d/01_films.sql:ro
      - ./backend/test/prac.schedules.sql:/docker-entrypoint-initdb.d/02_schedules.sql:ro
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./backend/.env
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  # mongo:
  #   image: mongo:7
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   restart: unless-stopped

volumes:
  frontend_dist:
  db_data:
  pgadmin_data:
  # mongo_data:
